spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cms
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  minio:
    url: http://minio:9000
    access-key: minioadmin
    secret-key: minioadmin123
  sql:
    init:
      mode: always