spring:
  application:
    name: headless-cms
  datasource:
    url: jdbc:postgresql://localhost:5432/headless_cms
    username: pourya
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  minio:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin123
  jackson:
    serialization:
      fail-on-empty-beans: false