spring:
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  application:
    name: headless-cms
  datasource:
    url: jdbc:postgresql://localhost:5432/headless_cms
    username: pourya
    password: 12345
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  minio:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin123
  jackson:
    serialization:
      fail-on-empty-beans: false
logging:
  level:
    root: debug